--- 
name: leposti
services: 
  - 
    github: 
      branch: front/ant-test-wysiwyg
      deploy_on_push: true
      repo: jbetancur12/leposti
    name: frontend
    routes: 
      - 
        path: /
    source_dir: frontend