--- 
name: leposti
static_sites: 
  - name: frontend 
    github: 
      branch: front/ant-test-wysiwyg
      deploy_on_push: true
      repo: jbetancur12/leposti
    routes: 
      - path: /
    source_dir: frontend